const ASSETS = [
  { name: "Bitcoin", symbol: "BTCUSDT" }, { name: "Ethereum", symbol: "ETHUSDT" },
  { name: "Solana", symbol: "SOLUSDT" }, { name: "XRP", symbol: "XRPUSDT" },
  { name: "Dogecoin", symbol: "DOGEUSDT" },
];
const API = "https://data-api.binance.vision/api/v3";
function ema(v,p){if(v.length<p)return null;const k=2/(p+1);let e=v.slice(0,p).reduce((a,b)=>a+b,0)/p;for(let i=p;i<v.length;i++)e=v[i]*k+e*(1-k);return e}
function rsi(v,p=14){if(v.length<p+1)return null;let g=0,l=0;for(let i=1;i<=p;i++){const d=v[i]-v[i-1];if(d>0)g+=d;else l-=d}g/=p;l/=p;for(let i=p+1;i<v.length;i++){const d=v[i]-v[i-1];g=(g*(p-1)+Math.max(d,0))/p;l=(l*(p-1)+Math.max(-d,0))/p}return l===0?100:100-100/(1+g/l)}
function macd(v){if(v.length<35)return null;function series(p){const k=2/(p+1);let e=v.slice(0,p).reduce((a,b)=>a+b,0)/p;const o=Array(p-1).fill(null);o.push(e);for(let i=p;i<v.length;i++){e=v[i]*k+e*(1-k);o.push(e)}return o}const a=series(12),b=series(26),line=v.map((_,i)=>a[i]==null||b[i]==null?null:a[i]-b[i]).filter(Number.isFinite);if(line.length<9)return null;const k=2/10;let sig=line.slice(0,9).reduce((x,y)=>x+y,0)/9;for(let i=9;i<line.length;i++)sig=line[i]*k+sig*(1-k);return{histogram:line.at(-1)-sig}}
function atr(cs,p=14){if(cs.length<p+1)return null;const tr=[];for(let i=1;i<cs.length;i++){const c=cs[i],q=cs[i-1];tr.push(Math.max(c.high-c.low,Math.abs(c.high-q.close),Math.abs(c.low-q.close)))}const t=tr.slice(-p);return t.reduce((a,b)=>a+b,0)/t.length}
function pattern(cs){if(cs.length<2)return"—";const c=cs.at(-1),p=cs.at(-2),b=Math.abs(c.close-c.open),r=Math.max(c.high-c.low,1e-12),u=c.high-Math.max(c.open,c.close),l=Math.min(c.open,c.close)-c.low;if(b/r<.1)return"Doji";if(c.close>c.open&&p.close<p.open&&c.open<=p.close&&c.close>=p.open)return"Bullish engulfing";if(c.close<p.close&&c.close<c.open&&p.close>p.open&&c.open>=p.close&&c.close<=p.open)return"Bearish engulfing";if(l>b*2&&u<b*1.2&&c.close>c.open)return"Hammer";if(u>b*2&&l<b*1.2&&c.close<c.open)return"Shooting star";return c.close>=c.open?"Bull candle":"Bear candle"}
function analyze(asset,cs){if(cs.length<60)throw Error("insufficient candles");const v=cs.map(x=>x.close),c=cs.at(-1),e9=ema(v,9),e21=ema(v,21),e50=ema(v,50),R=rsi(v),M=macd(v),A=atr(cs),pat=pattern(cs),avg=cs.slice(-21,-1).reduce((s,x)=>s+x.volume,0)/20,vr=avg>0?c.volume/avg:1,prior=cs.slice(-21,-1),hi=Math.max(...prior.map(x=>x.high)),lo=Math.min(...prior.map(x=>x.low));let score=0,reasons=[];if(c.close>e9&&e9>e21&&e21>e50){score+=2;reasons.push("EMA trend bullish")}else if(c.close<e9&&e9<e21&&e21<e50){score-=2;reasons.push("EMA trend bearish")}if(R>=55&&R<=70){score++;reasons.push("RSI "+R.toFixed(1))}else if(R>=30&&R<=45){score--;reasons.push("RSI "+R.toFixed(1))}if(M&&M.histogram>0){score++;reasons.push("MACD positive")}else if(M&&M.histogram<0){score--;reasons.push("MACD negative")}if(vr>=1.2){if(c.close>=c.open){score++;reasons.push("volume "+vr.toFixed(1)+"x")}else{score--;reasons.push("sell volume "+vr.toFixed(1)+"x")}}if(c.close>hi){score++;reasons.push("20-bar breakout")}else if(c.close<lo){score--;reasons.push("20-bar breakdown")}if(["Bullish engulfing","Hammer"].includes(pat)){score++;reasons.push(pat)}else if(["Bearish engulfing","Shooting star"].includes(pat)){score--;reasons.push(pat)}const action=score>=4?"BUY":score<=-4?"SELL":"WATCH",risk=Math.max((A||c.close*.003)*1.5,c.close*.001);return{asset:asset.name,symbol:asset.symbol,action,score,entry:c.close,target:action==="BUY"?c.close+risk*2:action==="SELL"?c.close-risk*2:null,stop:action==="BUY"?c.close-risk:action==="SELL"?c.close+risk:null,rsi:R,volumeRatio:vr,pattern:pat,reasons,candleCloseTime:c.closeTime}}
async function getCandles(asset){const r=await fetch(API+"/klines?symbol="+asset.symbol+"&interval=1m&limit=240");if(!r.ok)throw Error(asset.symbol+" API HTTP "+r.status);return(await r.json()).map(k=>({time:+k[0],open:+k[1],high:+k[2],low:+k[3],close:+k[4],volume:+k[5],closeTime:+k[6]})).filter(c=>[c.time,c.open,c.high,c.low,c.close,c.volume,c.closeTime].every(Number.isFinite))}
function fmt(n){if(!Number.isFinite(n))return"—";return n>=1000?n.toLocaleString("en-US",{maximumFractionDigits:2}):n>=1?n.toFixed(4):n.toFixed(7)}
async function sendTelegram(env,s){if(!env.TELEGRAM_BOT_TOKEN||!env.TELEGRAM_CHAT_ID)throw Error("Telegram secrets not configured");const emoji=s.action==="BUY"?"🟢":"🔴";const text=[emoji+" <b>AdaBot "+s.action+" • "+s.asset+"</b>","<b>Market:</b> "+s.symbol+" (1m)","<b>Price:</b> "+fmt(s.entry),"<b>Target:</b> "+fmt(s.target),"<b>Stop reference:</b> "+fmt(s.stop),"<b>Score:</b> "+s.score,"<b>RSI:</b> "+s.rsi.toFixed(1)+" • <b>Volume:</b> "+s.volumeRatio.toFixed(2)+"x","<b>Pattern:</b> "+s.pattern,"<b>Reasons:</b> "+s.reasons.join(", "),"<i>Analysis alert only—not an order. Verify independently. Spot SELL is not a short instruction.</i>"].join("\n");const r=await fetch("https://api.telegram.org/bot"+env.TELEGRAM_BOT_TOKEN+"/sendMessage",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:env.TELEGRAM_CHAT_ID,text,parse_mode:"HTML",disable_web_page_preview:true})});const b=await r.json();if(!r.ok||!b.ok)throw Error("Telegram delivery failed: "+(b.description||r.status))}
async function runScan(env){const settled=await Promise.allSettled(ASSETS.map(async a=>({asset:a,signal:analyze(a,await getCandles(a))}))),report={scannedAt:new Date().toISOString(),scanned:0,errors:[],signals:[]};for(const item of settled){if(item.status!=="fulfilled"){report.errors.push(String(item.reason?.message||item.reason));continue}report.scanned++;const{asset,signal}=item.value;report.signals.push(signal);const key="signal:"+asset.symbol,prev=await env.SIGNAL_STATE.get(key,"json"),fresh=signal.action!=="WATCH"&&(!prev||prev.action!==signal.action);if(fresh){try{await sendTelegram(env,signal);await env.SIGNAL_STATE.put(key,JSON.stringify({action:signal.action,candleCloseTime:signal.candleCloseTime,notifiedAt:Date.now()}))}catch(e){report.errors.push(asset.symbol+" alert: "+e.message)}}else if(!prev||prev.action!==signal.action){await env.SIGNAL_STATE.put(key,JSON.stringify({action:signal.action,candleCloseTime:signal.candleCloseTime,notifiedAt:null}))}}await env.SIGNAL_STATE.put("last-scan",JSON.stringify({scannedAt:report.scannedAt,scanned:report.scanned,errors:report.errors,signals:report.signals.map(({asset,symbol,action,score,entry,rsi,volumeRatio,pattern})=>({asset,symbol,action,score,entry,rsi,volumeRatio,pattern}))}),{expirationTtl:604800});console.log(JSON.stringify({scannedAt:report.scannedAt,scanned:report.scanned,errors:report.errors,signals:report.signals.map(s=>[s.symbol,s.action,s.score])}));return report}
export default{async fetch(request,env){const p=new URL(request.url).pathname;if(p==="/health")return Response.json({ok:true,service:"adabot-phase2",time:new Date().toISOString()});if(p==="/status")return Response.json(await env.SIGNAL_STATE.get("last-scan","json")||{status:"waiting-for-first-scan"},{headers:{"Cache-Control":"no-store"}});return new Response("AdaBot Phase 2 worker is running. See /health and /status.")},async scheduled(_event,env,ctx){ctx.waitUntil(runScan(env))}};
